---
sudo: required

env:
  - distro: centos7
    init: /usr/lib/systemd/systemd
  - distro: centos6
    init: /sbin/init

services:
  - docker

before_install:
  - docker pull geerlingguy/docker-${distro}-ansible

script:
  - container_id=$(mktemp)
  - docker run --detach --rm --volume=${PWD}:/etc/ansible/ geerlingguy/docker-${distro}-ansible ${init} > ${container_id}
  - docker exec $(cat $container_id) ansible-playbook /etc/ansible/playbooks/test.yml



