---

- hosts: localhost
  gather_facts: no
  become: true

  tasks:
    # - name: install epel-release package
    #   package:
    #     name: 
    #       - epel-release
    #     state: present

    - name: install epel-release package
      shell:
        cmd: amazon-linux-extras install epel -y

    - name: install nginx package
      package:
        name: 
          - nginx
        state: present

    - name: enable nginx service
      service:
        name: nginx
        state: started
        enabled: yes
