---
- hosts: localhost
  become: yes
  gather_facts: no


  tasks:
    - name: date
      command: date
      register: date_res
      changed_when: false

    - name: show date
      debug:
        var: date_res.stdout


